### ISSUE TITLE
Adding more Exif Tags

### ISSUE THREAD

**Issue by PaulDebus** [JuliaImages/ExifViewer.jl#11]
Hey, 

first of all: Cool package! This comes in handy in my workflow.

I am working with images, that do have EXIF Tags that the package currently does not support. Reading them gives me a lot of this:

```
  "<invalid #29>"                        => "2022:08:17"
  "<invalid #6>"                         => "239.515"
  "<invalid #5>"                         => "Sea level"
```
How would I go about adding them to the library? Just make a pull request? Or is there a more generic way to read those? When I look at the image metadata in the default Ubuntu image viewer, it shows all/most of them just fine.

Thanks for the support!
Paul

**Comment by ashwani-rathee** [comment]
Hey Paul!!
Can you share name of the Tags that are showing error or a sample image that holds that data so I can start figuring it out? I thought read_tags is unlikely to have errors but not really :)

You can make a PR but we need info on Tags that are showing error as it's likely that LibExif itself doesn't support them and we support tags only that LibExif supports at the current point. Looking forward to fixing this before next release.

**Comment by PaulDebus** [comment]
Hey,

I used the `exiftool` on Ubuntu to read the EXIF data and uploaded both results: 
- ExifViewer: https://gist.github.com/PaulDebus/2cfa442d99f22d96ce6360e85e18da68
- exiftool: https://gist.github.com/PaulDebus/01f74b4c03811d360f210ea6f144af57

The tags that result in an `<invalid ###>` key are:
- `GPS Track` for invalid 15
- `GPS Longitude` or `GPS Flight Longitude` for invalid 4
- `GPS Speed` for invalid 13
- `GPS Longitude Ref` for invalid 3
- `GPS Yaw Ref` (or similar) for invalid 14
- `Digital Creation Date` or `GPS Date Stamp` for invalid 29
- `GPS Flight Altitude` for invalid 6
- `GPS Altitude Ref` for invalid 5
- `GPS Time Stamp` for invalid 7
- and invalid 12 is not present in the `exiftool` output at all

So I guess the main point is, that there is a lot of GPS information (we use images from drones, btw.) that are not processed yet

Also, the `exiftool` produces 166 lines of output while the `ExifViewer` only reads 45 entries.

I cannot publicly share the images, but if you give me an email address, I can share some with you. 

Thanks for the support!

**Comment by ashwani-rathee** [comment]
Hey Paul,

It's very likely that LibExif is unable to read some tags as shown in these tests here where LibExif is trying to parse a image(in same folder) and just unable to parse

Image: https://github.com/libexif/libexif/blob/master/test/testdata/pentax_makernote_variant_4.jpg
Parsed with unknowns: https://github.com/libexif/libexif/blob/master/test/testdata/pentax_makernote_variant_4.jpg.parsed

Also, issue can be that camera model is not supported well or which software it was written using. Can you share a few images at ab669522@gmail.com , from there on I can start to look for a solution to this problem.

**Comment by ashwani-rathee** [comment]
Support for GPS tags has been added!

**Comment by PaulDebus** [comment]
Awesome! Thank you so much
