### ISSUE TITLE
Binaries for Mac Silicon

### ISSUE THREAD

**Issue by VEZY** [JuliaImages/ExifViewer.jl#17]
Would it be possible to make binaries for ARM-based Macs ?

**Comment by ashwani-rathee** [comment]
Hey @VEZY , can you please tell what specific issues are you facing? I checked the CI and there is support for MacOS, albeit we might need a little something more for ARM based ones

**Comment by VEZY** [comment]
Yes looking at the code [here](https://github.com/JuliaBinaryWrappers/libexif_jll.jl/blob/master/src/wrappers) it seems only x86/64 is supported for MacOS. And [looking at the latest release](https://github.com/JuliaBinaryWrappers/libexif_jll.jl/releases/tag/libexif-v0.6.21%2B0) confirm there is no tarball for aarch64 (e.g. something like `libexif.v0.6.21.aarch64-apple-darwin.tar.gz`). 

I don't have access to my mac right now, but the error was that it didn't find `libexif` in the module `LibExif`. So I tried to install libexif_jll.jl manually, and indeed the path was empty, because there is no tarball for apple silicon.

Maybe the rules for building with apple silicon where added after the release ? I see that the latest is from January 2020, so it would be possible.

**Comment by ashwani-rathee** [comment]
We should be in a better state in regards to support for ARM MacOS after this PR gets merged: https://github.com/JuliaPackaging/Yggdrasil/pull/6294 and we will have access to new version of libexif too. I'll make the neccessary changes here in ExifViewer.jl soon

**Comment by VEZY** [comment]
Awesome ! Thank you!
