### ISSUE TITLE
julia lts (1.6.7) unsupported

### ISSUE THREAD

**Issue by t-bltg** [JuliaImages/ExifViewer.jl#27]
Is there any reason why the LTS version of julia was unsupported from the beginning ?

**Comment by ashwani-rathee** [comment]
Reason was me thinking that it's better to have the latest version as supported, we should add compat as 1.6 if it's affecting anything

**Comment by t-bltg** [comment]
Alright, usually it is best to broaden Julia compatibility, and support at least lts, since currently I can't install it.
Sometimes (e.g. on hpc clusters) only older releases are installed by sysadmins.

**Comment by ashwani-rathee** [comment]
Let's do that sire :)

**Comment by t-bltg** [comment]
Thanks !
